### ISSUE TITLE
Fix several small issues with a Slack command integration

### ISSUE THREAD

**Issue by shaharsol** [tikalk/ttt-slack#6]
The original project is well described here: #3 

After a soft launch to several employees we received some feedback and require some minor modifications
1. A plain `/ttt` should response with a help text describing the options of the command (like a `--help` of a command line)
2. Please don't show the password in plain text for the user. Mark *****\* for an existing password.
3. Our entire team is located at GMT+2 (actually its now GMT+3 because of DST but the system should be able to be aware to that), but the server time is GMT. So the `/in` and `/out` commands should work accordingly and not report everything as 2-3 hours earlier...
4. Add an optional {date} param as the last param for the `/track` command. Format should be yyyy-mm-dd.

codemill $20

**Comment by shaharsol** [comment]
codemill$20

**Comment by blitmap** [comment]
Hmm, I'd be happy to work on this again - but isn't not listed on Codemill for some reason.  Has it already been grabbed?  I thought I'd see a "... has been assigned" thing.

1) If you like I can start working on it anyway until Codemill becomes seemingly less confused. :smile:

2) The password is shown because the reply is only visible to the person who issued the command.  You would like it hidden anyway?

3) I'm not sure there's a way I can detect what timezone the person issuing the command is in.  I could add support for a default timezone and also add a new command for setting your timezone.  Would this be okay?  Anuko tracks the registered events in UTC, so this is only really about translating this from/to what the user issues in Slack, yes?

**Comment by shaharsol** [comment]
It's not listed yet because I haven't approved payment yet... Something
else caught my attention. Will be back to it soon...

**Comment by khuongduybui** [comment]
I'm really tempted to grab this just for fun :)) but I'll let blitmap take it first :dancer:

**Comment by blitmap** [comment]
I feel like I had an unfair advantage to grab it, Github notified me about this issue because of my prior contribution to ttt-slack before Codemill listed it.  Anyway, I'll do my best! :smile:

**Comment by shaharsol** [comment]
@blitmap wow you're quick.

About the password, the person is sitting at a desktop, and someone can look over their shoulder...

About the TZ, I'm not sure what the right solution is. I'm pretty sure our production Anuko is sitting on a server with a TZ configured to GMT+2. and I'm running this server and the proxy on a heroku server which I'm sure are set to GMT.

**Comment by shaharsol** [comment]
so when a user uses `/ttt in` or `/ttt out` I bet it used the GMT time. 
When a user does a `/track` I have a feeling its OK but need to verify that

**Comment by shaharsol** [comment]
@blitmap on another issue, any chance you can sign up with [gitter.im](http://gitter.im) so we can discuss something in private?

**Comment by khuongduybui** [comment]
1. It's also safer to mask passwords in return. However, someone can look over when they enter the command /ttt password anyway, can't they? Just some thought.
2. If we know for sure our users are located in a timezone, we can explicitly set that on the moment object before we save. Moment can take care of daylight saving if you use a locale tz (e.g. America/New York) instead of absolute tz (e.g. GMT-5)

**Comment by blitmap** [comment]
This just happened to be exactly when I got up for the day. :smile:

1) Okay, I can either hide the password and show it as asterisks - or not show it at all, which would you prefer?

2) I'm going to see if Slack advertises the timezone the user issues the command from somehow.

3) I'm now on gitter.im, what should I do?  Is there a room I should join?

**Comment by shaharsol** [comment]
I believe the user needs some feedback re whether their password is set or not. So I'm in favor of asteriks. If it's not set, the `undefined` is informative...

**Comment by shaharsol** [comment]
If you're going to use @khuongduybui advice about the locale, we're in Israel FYI, not sure what the exact locale string is...

**Comment by blitmap** [comment]
1) It looks as if Israel is `IST` when no daylight savings is in effect, or `IDT` when it is.  `UTC+2` or `UTC+3`

2) I'd like to suggest making the date a required parameter for `/ttt track`, it would be a bit messier to make it an optional argument since `note` is the current optional argument.  I will do only what you ask, do you want `date` to be optional?

**Comment by blitmap** [comment]
Yeah, it gets really difficult to determine if a `date` is present in `/ttt track` because the optional `note` argument is variable in length.

I could do it by trying to parse the first part of the `note` with moment.js and seeing if it passes, but it'd be much cleaner if we require the `date` or remove the `note`.  It is completely your decision :smile:

**Comment by shaharsol** [comment]
Let's get rid of note altogether so we can use date as optional.

**Comment by blitmap** [comment]
Understood. :smile:

If notes are something you don't expect to make use of, would you also want me to remove the unrelated `/ttt note` command when not using `/ttt track ...`?

**Comment by shaharsol** [comment]
Hehe didn't even know it existed.

**Comment by blitmap** [comment]
So.... I should remove it? :smile:

**Comment by blitmap** [comment]
I'm going to create a pull request but it isn't yet finished.  I just want you to be in the loop on my progress.

I am still working on the timezone translation.

**Comment by shaharsol** [comment]
Yes, remove it please. as for the PR, I can wait until all is done.
